pipeline {
    agent any    
    environment {
        MAVEN_HOME = "/opt/apache-maven-3.9.8"
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Verify Maven') {
            steps {
                sh 'mvn -v' // Check Maven version to confirm it's installed
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Completed') {
            steps {
                echo "Completed!"
            }
        }
    }
}
